#!/bin/bash
# imgcd self-extracting bundle (makeself-style)
# This script contains an embedded tar.gz payload with imgcd binary and image data
# Generated by imgcd - https://github.com/so2liu/imgcd

set -e

# Metadata (will be replaced during generation)
TARGET_PLATFORM="{{TARGET_PLATFORM}}"
IMAGE_NAME="{{IMAGE_NAME}}"
IMGCD_VERSION="{{IMGCD_VERSION}}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Detect current platform
detect_platform() {
    local os=$(uname -s | tr '[:upper:]' '[:lower:]')
    local arch=$(uname -m)

    case "$arch" in
        x86_64)
            arch="amd64"
            ;;
        aarch64|arm64)
            arch="arm64"
            ;;
        *)
            echo -e "${RED}Error: Unsupported architecture: $arch${NC}" >&2
            exit 1
            ;;
    esac

    echo "${os}/${arch}"
}

# Main execution
main() {
    echo "imgcd self-extracting bundle v${IMGCD_VERSION}"
    echo "Target platform: ${TARGET_PLATFORM}"
    echo "Image: ${IMAGE_NAME}"
    echo ""

    # Detect current platform
    CURRENT_PLATFORM=$(detect_platform)
    echo "Detected platform: ${CURRENT_PLATFORM}"

    # Warn if platforms don't match
    if [ "$CURRENT_PLATFORM" != "$TARGET_PLATFORM" ]; then
        echo -e "${YELLOW}Warning: Current platform ($CURRENT_PLATFORM) differs from target platform ($TARGET_PLATFORM)${NC}"
        echo -e "${YELLOW}The embedded imgcd binary may not be compatible with this system.${NC}"
        read -p "Continue anyway? (y/N) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "Aborted."
            exit 1
        fi
    fi

    # Create temporary directory
    TEMP_DIR=$(mktemp -d -t imgcd-bundle.XXXXXX)
    trap "rm -rf $TEMP_DIR" EXIT

    echo ""
    echo "Extracting bundle..."

    # Find the line number of the payload marker
    # Use -a to force grep to treat the file as text (important for large binary payloads)
    PAYLOAD_LINE=$(grep -a -n '^__PAYLOAD_BELOW__$' "$0" | head -1 | cut -d: -f1)
    if [ -z "$PAYLOAD_LINE" ]; then
        echo -e "${RED}Error: Payload marker not found${NC}" >&2
        exit 1
    fi

    # Extract payload (tar.gz containing imgcd + image.tar.gz)
    # Skip to the line after the marker and extract the tar.gz
    tail -n +$((PAYLOAD_LINE + 1)) "$0" | tar xzf - -C "$TEMP_DIR"

    # Verify extraction
    if [ ! -f "$TEMP_DIR/imgcd" ] || [ ! -f "$TEMP_DIR/image.tar.gz" ]; then
        echo -e "${RED}Error: Failed to extract bundle contents${NC}" >&2
        exit 1
    fi

    chmod +x "$TEMP_DIR/imgcd"

    echo "Extraction complete."
    echo ""
    echo "Loading image into container runtime..."

    # Load the image using the extracted imgcd binary
    if "$TEMP_DIR/imgcd" load --from "$TEMP_DIR/image.tar.gz"; then
        echo ""
        echo -e "${GREEN}Successfully loaded image: ${IMAGE_NAME}${NC}"
        exit 0
    else
        echo ""
        echo -e "${RED}Failed to load image${NC}" >&2
        exit 1
    fi
}

# Run main function
main "$@"
